#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
#  
# <https://github.com/KFERMercer/OpenWrt-CI>
# 
name: Merge-upstream

on:
#   push:
#     branches: 
#       - master
  schedule:
    - cron: 30 19 * * *
  push:
    branches: 
      - dev
  release:
     types: [published]

jobs:
  merge:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: dev-master
        fetch-depth: 0
        lfs: true
        
    - name: Set git identity
      run : |
        git config --global user.email "manyu34@gmail.com"
        git config --global user.name "LesLis.W"
    
    - name: Load upstream dev-master commits
      run: git pull -f https://github.com/Lienol/openwrt.git dev-master:dev-master --no-edit --strategy-option ours
   
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: dev-master
      run: git push -f origin $DOWNSTREAM_BRANCH
    
    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: dev-19.07
        fetch-depth: 0
        lfs: true
   
    - name: Load upstream 19.07 commits
      run: git pull -f https://github.com/Lienol/openwrt.git dev-19.07:dev-19.07 --no-edit --strategy-option ours
   
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: dev-19.07
      run: git push -f origin $DOWNSTREAM_BRANCH

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: dev-lean-lede
        fetch-depth: 0
        lfs: true
    
    - name: Load upstream dev-lean-lede commits
      run: git pull -f https://github.com/Lienol/openwrt.git dev-lean-lede:dev-lean-lede --no-edit --strategy-option ours
   
    - name: Push Commits
      env:
        DOWNSTREAM_BRANCH: dev-lean-lede
      run: git push -f origin $DOWNSTREAM_BRANCH
